# Generated by Django 4.2.1 on 2023-06-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KioscoDeCarlitos', '0002_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=200)),
                ('producto_precio', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('producto_cantidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
